repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    args: ["--profile", "black"]
- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
- repo: local
  hooks:
  - id: flake8-custom
    name: flake8 with pyproject.toml support
    additional_dependencies: ['pyproject-flake8']
    entry: pflake8 .
    files: '.py$'
    language: python
- repo: https://github.com/python-poetry/poetry
  rev: "1.7.0"
  hooks:
    - id: poetry-check
    - id: poetry-lock
    - id: poetry-export
      args: ["-f", "requirements.txt", "-o", "requirements.txt"]
    - id: poetry-export
      args: ["--only", "dev", "-f", "requirements.txt", "-o", "requirements-dev.txt"]